### ISSUE TITLE
Inconsistencies for MouseButton types

### ISSUE THREAD

**Issue by mkrus** [KDAB/KDUtils#4]
MousePressEvent and others contain a member of type MouseButtons (with the s). This is defined as a KDFlag of MouseButton (no s) enum values.

MouseButtons is designed to indicate the current state of all the buttons.
MouseButton only refers to a single button.

But all current backends use the id of the button that triggered the event to initialise the MousePressEvent object. This means that:
- the event member should actually just be of type MouseButton
- it is up to the application to track the state of all buttons (for example to handle the case where both left and right buttons are pressed one after the other)

Qt events for example have both a button property (the button that triggered the event) and a buttons property (the state of all the buttons).

Simple fix would be to change MousePressEvent to have a MouseButton property (no s). More complete fix would be to add MouseButton and MouseButtons (backends would need to track that now).

**Comment by seanharmer** [comment]
I think Milosz is planning on adding this.

**Comment by MiKom** [comment]
Should be fixed by https://github.com/KDAB/KDUtils/commit/9f71fbc676dd022c1c7ab92e972d9c1ec91c2d6e

I tested it on windows, x11, wayland and macOS and seems to work properly.
